name: Django CI

on: 
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: nimrimah1234567
          POSTGRES_DB: todoapp-db
        ports:
          - 5432:5432
        options: >
          --health-cmd "pg_isready -U admin"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install libpq-dev
      run: sudo apt-get install -y libpq-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h db -p 5432 -U admin; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Run migrations
      env:
        DATABASE_URL: postgres://admin:nimrimah1234567@db:5432/todoapp-db
      run: python manage.py migrate

    - name: Run tests
      run: |
        flake8 .
        pytest .