name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:

      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: a/@123456
          POSTGRES_DB: todoapp-db
        ports:
          - 5432:5432
        options: 
          --health-cmd pg_isready
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
  
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-django
        cd core
        python manage.py migrate

    - name: Run Tests
      run: |
        python manage.py test